routes/web.php
<?php

use App\Http\Controllers\Client\CompanyController;
use App\Http\Controllers\Client\EmployerController;
use App\Http\Controllers\Client\MajorsController;
use App\Http\Controllers\Employer\HomeController;
use App\Http\Controllers\Employer\NewEmployerController;
use App\Http\Controllers\Employer\PackageController;
use App\Http\Controllers\Employer\PaymentForEmployerController;
use App\Http\Controllers\Employer\PaymentHistoryController;
use App\Http\Controllers\Employer\ProfileCompanyController;
use App\Http\Controllers\Employer\ProfileEmployerController;
use App\Http\Controllers\Employer\SearchCvController;
use App\Http\Controllers\FagsController;
use App\Http\Controllers\HomeController as ControllersHomeController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\Seeker\ManageController;
use App\Http\Controllers\Seeker\ProfileController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// login
Route::resource('/login', LoginController::class);
Route::prefix('login')->name('login.')->group(function () {
    Route::post('/dang-ky', [LoginController::class, 'register'])->name('register');
    Route::post('/dang-nhap', [LoginController::class, 'store'])->name('store');
});
// home
Route::get('/', [ControllersHomeController::class, 'index'])->name('home');

// xác thực tài khoản
Route::get('xac-thuc-tai-khoan', [LoginController::class, 'activeUser'])->name('activeUser');
//register employer

Route::get('nha-tuyen-dung/dang-ky', [EmployerController::class, 'index'])->name('register');
Route::post('nha-tuyen-dung/dang-ky', [EmployerController::class, 'store'])->name('register.store');

//
Route::prefix('viec-lam')->name('client.')->group(function () {
    Route::get('/{slug}.{id}', [ControllersHomeController::class, 'detail'])->name('detail');
    Route::post('/up-cv', [ControllersHomeController::class, 'upCv'])->name('upcv');
    // love cv
    Route::get('/favourite-love/{id}', [ControllersHomeController::class, 'getDatalove']); // api
    Route::post('/favourite/{id}', [ControllersHomeController::class, 'userFavouriteId']); // api\

    // nganh nghe
    Route::resource('nganh-nghe', MajorsController::class);
});

// client company
Route::prefix('cong-ty')->name('company.')->group(function () {
    Route::get('/{id}', [CompanyController::class, 'detail'])->name('detail');
    Route::get('/', [CompanyController::class, 'index'])->name('index');
});


// faqs
Route::resource('faqs', FagsController::class);

// search job
Route::get('/search', [ControllersHomeController::class, 'search'])->name('home.search');

Route::middleware('checkLogin')->group(function () {
    // client user
    Route::prefix('users')->name('users.')->group(function () {

        Route::prefix('profile')->name('profile.')->group(function () {
            Route::get('/{slug}', [ProfileController::class, 'index'])->name('index');
            Route::post('/update-image-user', [ProfileController::class, 'changeImage'])->name('changeImage');
            Route::post('/on-status-profile', [ProfileController::class, 'onStatus'])->name('onStatus');
            Route::post('/off-status-profile', [ProfileController::class, 'offStatus'])->name('offStatus');
        });
        Route::resource('file', ManageController::class);
        Route::prefix('file')->name('file.')->group(function () {
            Route::get('destroy/{id}', [ManageController::class, 'destroy'])->name('destroy');
            Route::get('/cv/create-cv', [ManageController::class, 'createCv'])->name('createCv');
            Route::post('/cv/create-cv', [ManageController::class, 'createFormCv'])->name('createFormCv');
        });
        Route::get('apply', [ManageController::class, 'apply'])->name('apply');
        Route::get('love', [ManageController::class, 'love'])->name('love');
        Route::prefix('love')->group(function () {
            Route::delete('delete-love-cv', [ManageController::class, 'deleteLoveCv'])->name('deleteLoveCv');
        });
        Route::get('change-password', [ProfileController::class, 'changePassword'])->name('changePassword');
        Route::post('change-password', [ProfileController::class, 'changePasswordSucsses'])->name('changePasswordSucsses');
        // 
        Route::get('get-data-reason/{id}', [ManageController::class, 'getDataReason'])->name('getDataReason');
    });

    // logout
    Route::get('logout', [LoginController::class, 'logout'])->name('logout');

    // ntd 
    Route::middleware('checkEmployer')->group(function () {
        Route::prefix('employers')->name('employer.')->group(function () {
            Route::get('/', [HomeController::class, 'index'])->name('index');
            Route::resource('/new', NewEmployerController::class);
            Route::prefix('/new')->name('new.')->group(function () {
                Route::post('/update/{id}', [NewEmployerController::class, 'update'])->name('update');
                Route::get('/{id}', [NewEmployerController::class, 'destroy'])->name('destroy');
                Route::get('change-status-cv/{id}', [NewEmployerController::class, 'changeStatusCv'])->name('changeStatusCv');
                Route::post('update-reason-cv', [NewEmployerController::class, 'reasonCv'])->name('reasonCv');
                Route::get('get-data-reason/{id}', [NewEmployerController::class, 'getDataReason'])->name('getDataReason');
                Route::get('job/top-new', [NewEmployerController::class, 'topNew'])->name('topNew');
                Route::post('job/top-new', [NewEmployerController::class, 'upTopNew'])->name('upTopNew');
                Route::post('job/delete-top-new/{id}', [NewEmployerController::class, 'deleteTopNew'])->name('deleteTopNew');
                Route::get('cv/get-data-cv-refuse', [NewEmployerController::class, 'refuse'])->name('refuse');
                Route::get('cv/get-data-cv-filter-apply', [NewEmployerController::class, 'filterApply'])->name('filterApply');
                Route::delete('delete/cv/filter-apply/{id}', [NewEmployerController::class, 'deletefilterApply'])->name('deletefilterApply');
            });
            // submitted work
            Route::get('submitted-work', [NewEmployerController::class, 'submittedWork'])->name('submittedWork');
            // 
            Route::resource('/package', PackageController::class);
            Route::resource('/profile', ProfileEmployerController::class);
            Route::resource('/company', ProfileCompanyController::class);
            Route::prefix('/company')->name('company.')->group(function () {
                Route::get('new/business', [ProfileCompanyController::class, 'business'])->name('business');
                Route::post('new/business', [ProfileCompanyController::class, 'ImageAccuracy'])->name('ImageAccuracy');
            });
            Route::prefix('/package')->name('package.')->group(function () {
                Route::post('/payment', [PackageController::class, 'payment'])->name('payment');
                Route::get('package/payment/return', [PackageController::class, 'vnpayReturn'])->name('return');
                Route::get('package/payment/output', [PackageController::class, 'vnpayOutput'])->name('output');
                Route::post('package/payment/update-time/{id}', [PackageController::class, 'updateTimePayment'])->name('updateTimePayment');
                Route::post('package/payment/upgrade-package/{id}', [PackageController::class, 'upgradePackage'])->name('upgradePackage');
            });
            // search cv
            Route::get('search-cv', [SearchCvController::class, 'index'])->name('search.cv');
            Route::get('search-cv/{id}', [SearchCvController::class, 'show'])->name('search.show');
            Route::post('payment-cv', [SearchCvController::class, 'paymentCv'])->name('search.paymentCv');
            Route::post('search-cv/feedback', [SearchCvController::class, 'feedback'])->name('search.feedback');
            Route::get('cv-bought', [SearchCvController::class, 'showCvBought'])->name('cvbought');
            // nap  tiền
            Route::resource('payment-for-emplyer', PaymentForEmployerController::class);
            Route::prefix('/payment-for-emplyer')->name('payment-for-emplyer.')->group(function () {
                Route::get('payment/vnpay-return', [PaymentForEmployerController::class, 'vnpayReturn'])->name('vnpayReturn');
            });
            Route::resource('payment-history', PaymentHistoryController::class);
            // đoi mk
            Route::get('change-password', [HomeController::class, 'changePassword'])->name('changePassword');
            Route::post('change-password', [HomeController::class, 'changePasswordSucsses'])->name('changePasswordSucsses');
        });
    });
});

resources/views/index.blade.php
@extends('layouts.index')
@section('home')
    <section>
        <div class="block no-padding">
            <div class="container fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="main-featured-sec">
                            <div class="new-slide">
                                <img src="{{ asset('home/images/resource/vector-1.png') }}">
                            </div>
                            <div class="job-search-sec">
                                <div class="job-search">
                                    <h3>Cách dễ nhất để có được công việc mới của bạn</h3>
                                    <span>Tìm Việc Làm, Việc Làm & Cơ Hội Nghề Nghiệp</span>
                                    <form action="{{ route('home.search') }}">
                                        <div class="row">
                                            <div class="col-lg-7 col-md-5 col-sm-12 col-xs-12">
                                                <div class="job-field">
                                                    <input type="text" name="key" class="form-control"
                                                        placeholder="Tìm kiếm...." />
                                                    <i class="la la-keyboard-o"></i>
                                                </div>
                                            </div>
                                            <div class="col-lg-4 col-md-5 col-sm-12 col-xs-12">
                                                <div class="job-field">
                                                    <select class="form-control" name="location" style="height: 62px;">
                                                        <option value="">....Chọn địa chỉ....</option>
                                                        @foreach ($location as $value)
                                                            <option value="{{ $value->id }}">{{ $value->name }}</option>
                                                        @endforeach
                                                    </select>
                                                    <i class="la la-map-marker"></i>
                                                </div>
                                            </div>
                                            <div class="col-lg-1 col-md-2 col-sm-12 col-xs-12">
                                                <button type="submit"><i class="la la-search"></i></button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                            <div class="scroll-to">
                                <a href="#scroll-here" title=""><i class="la la-arrow-down"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <br>
    <section id="scroll-here">
        <div class="block">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="heading">
                            <h2>Việc làm nổi bật</h2>
                            <span>Các nhà tuyển dụng hàng đầu đã sử dụng công việc và nhân tài.</span>
                        </div><!-- Heading -->
                        <div class="job-listings-sec" id="paginated-list">
                            @foreach ($job as $item)
                                <div class="job-listing render-job-search">
                                    <div class="job-title-sec">
                                        <div class="c-logo"> <img src="{{ asset($item->logo) }}" alt="" />
                                        </div>
                                        <h3><a href="{{ route('client.detail', [$item->slug, $item->id]) }}"
                                                title="">{{ $item->title }}</a></h3>
                                        <span><a
                                                href="{{ route('company.detail', $item->idCompany) }}">{{ $item->nameCompany }}</a></span>
                                    </div>
                                    <span class="job-lctn"><i
                                            class="la la-map-marker"></i>{{ $item->getlocation->name }}</span>
                                    <span class="fav-job">{{ $item->end_job_time }}</span>
                                    <span class="job-is ft">{{ $item->getTime_work->name }}</span>
                                </div><!-- Job -->
                            @endforeach
                        </div>
                        {{-- paginate --}}
                        <div class="row">
                            <div class="col-lg-12 col-md-12 col-sm-12 job-list browse-all-cat">
                                <span class="text-center p-3 ">
                                    <div id="pagination-numbers" style="margin-bottom: 20px">
                                    </div>
                                </span>
                            </div>
                        </div>
                        {{-- end paginate --}}
                    </div>

                </div>
            </div>
        </div>
    </section>


    <section>
        <div class="block double-gap-top double-gap-bottom">
            <div data-velocity="-.1"
                style="background: url({{ asset('home/images/resource/parallax1.jpg') }}) repeat scroll 50% 422.28px transparent;"
                class="parallax scrolly-invisible layer color"></div><!-- PARALLAX BACKGROUND IMAGE -->
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="simple-text-block">
                            <h3>Tạo sự khác biệt với Sơ yếu lý lịch trực tuyến của bạn!!</h3>
                            <span>Sơ yếu lý lịch của bạn trong vài phút với trợ lý sơ yếu lý lịch JobHunt đã sẵn
                                sàng!</span>
                            <a href="" title="">Tạo một tài khoản</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section>
        <div class="block">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="heading">
                            <h2>Ngành nghề trọng điểm</h2>
                            <span>{{ $countJob }} Việc làm hiện có</span>
                        </div><!-- Heading -->
                        <div class="cat-sec">

                            <div class="row no-gape">
                                @foreach ($majors as $value)
                                    <div class="col-lg-3 col-md-3 col-sm-6">
                                        <div class="p-category">
                                            <a href="{{ route('client.nganh-nghe.show', $value->id) }}" title="">
                                                <i class="{{ $value->image_majors }}"></i>
                                                <span>{{ $value->name }}</span>
                                                <p>({{ count($value->majors) }} Việc làm)</p>
                                            </a>
                                        </div>
                                    </div>
                                @endforeach
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section id="scroll-here">
        <div class="block">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="heading">
                            <h2>Việc làm hấp dẫn</h2>
                            <span>Các nhà tuyển dụng hàng đầu đã sử dụng công việc và nhân tài.</span>
                        </div><!-- Heading -->
                        <div class="job-listings-sec">
                            @foreach ($jobAttractive as $item)
                                <div class="job-listing">
                                    <div class="job-title-sec">
                                        <div class="c-logo"> <img src="{{ asset($item->logo) }}" alt="" />
                                        </div>
                                        <h3><a href="{{ route('client.detail', [$item->slug, $item->id]) }}"
                                                title="">{{ $item->title }}</a></h3>
                                        <span style="margin-left: 1px !important"><a
                                                href="{{ route('company.detail', $item->idCompany) }}">{{ $item->nameCompany }}</a></span>
                                    </div>
                                    <span class="job-lctn"><i
                                            class="la la-map-marker"></i>{{ $item->getlocation->name }}</span>
                                    <span class="fav-job">{{ $item->end_job_time }}</span>
                                    <span class="job-is ft">{{ $item->getTime_work->name }}</span>
                                </div><!-- Job -->
                            @endforeach
                        </div>
                    </div>
                </div>
                <div class="box-next-index text-center mt-5">
                    <a href="{{ route('home.search') }}" class="btn btn-primary">Xem tất cả</a>
                </div>
            </div>
        </div>
    </section>
    <section>
        <div class="block">
            <div data-velocity="-.1"
                style="background: url({{ asset('home/images/resource/parallax3.jpg') }}) repeat scroll 50% 422.28px transparent;"
                class="parallax scrolly-invisible no-parallax"></div>
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="heading">
                            <h2>Tin tức</h2>
                        </div><!-- Heading -->
                        <div class="blog-sec">
                            <div class="row">
                                @foreach ($news as $item)
                                    <div class="col-lg-4">

                                        <div class="my-blog">
                                            <div class="blog-thumb">
                                                <a href="" title=""><img
                                                        src="{{ env('IMAGE') . $item->new_image }}" alt="" /></a>
                                                <div class="blog-metas">
                                                    <a href="" title="">{{ $item->created_at }}</a>
                                                </div>
                                            </div>
                                            <div class="blog-details">
                                                <h3><a href="" title="">{{ $item->title }}</a></h3>
                                                <p>{{ $item->describe }}</p>
                                            </div>
                                        </div>
                                    </div>
                                @endforeach
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section>
        <div class="block no-padding">
            <div class="container fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="simple-text">
                            <h3>Liên hệ với chúng tôi</h3>
                            <span>Chúng tôi ở đây để giúp đỡ. Kiểm tra Câu hỏi thường gặp của chúng tôi, gửi email cho chúng
                                tôi hoặc gọi cho chúng tôi theo số 1 (800) 555-5555</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/jobDetail.blade.php
@extends('layouts.index')
@section('home')
    <section class="overlape">
        <div class="block no-padding">
            <div data-velocity="-.1"
                style="background: url({{ asset('home/images/resource/mslider1.jpg') }}) repeat scroll 50% 422.28px transparent;"
                class="parallax scrolly-invisible no-parallax"></div><!-- PARALLAX BACKGROUND IMAGE -->
            <div class="container fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="inner-header">
                            <h3>{{ $job->title }}</h3>
                            <div class="job-statistic">
                                <span>{{ $job->getTime_work->name }}</span>
                                <p><i class="la la-map-marker"></i> {{ $job->getlocation->name }}</p>
                                <p><i class="la la-calendar-o"></i>{{ $job->getExperience->name }}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section>
        <div class="block">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 column">
                        <div class="job-single-sec">
                            <div class="job-single-head">
                                <div class="job-thumb"> <img src="{{ asset($job->logo) }}" alt="" /> </div>
                                <div class="job-head-info">
                                    <h4>{{ $job->title }}</h4>
                                    <span><a
                                            href="{{ route('company.detail', $job->idCompany) }}">{{ $job->nameCompany }}</a></span>
                                    <p><i class="la la-envelope-o"></i> {{ $job->emailCompany }}</p>
                                </div>
                            </div><!-- Job Head -->
                            <div class="job-details">
                                <h3>Mô tả công việc</h3>
                                <p>{!! $job->describe !!}</p>
                                <h3>Kiến thức, kỹ năng và khả năng cần thiết</h3>
                                <p>{!! $job->candidate_requirements !!}</p>
                                <h3>Phúc lợi</h3>
                                <p>{!! $job->benefit !!}</p>
                            </div>
                            <div class="share-bar">
                                <span>Share</span><a href="#" title="" class="share-fb"><i
                                        class="fa fa-facebook"></i></a><a href="#" title=""
                                    class="share-twitter"><i class="fa fa-twitter"></i></a>
                            </div>
                            <div class="recent-jobs">
                                <h3>Công việc liên quan</h3>
                                <div class="job-list-modern">
                                    <div class="job-listings-sec no-border">
                                        @foreach ($rules as $rule)
                                            <div class="job-listing wtabs">
                                                <div class="job-title-sec">
                                                    <div class="c-logo"> <img src="{{ asset($rule->logo) }}"
                                                            alt="" />
                                                    </div>
                                                    <h3><a href="{{ route('client.detail', [$rule->slug, $rule->id]) }}"
                                                            title="">{{ $rule->title }}</a></h3>
                                                    <div class="job-lctn"><i
                                                            class="la la-map-marker"></i>{{ $rule->address }}
                                                    </div>
                                                </div>
                                                <div class="job-style-bx">
                                                    <span class="job-is ft">{{ $rule->getTime_work->name }}</span>
                                                    <i>{{ $rule->end_job_time }}</i>
                                                </div>
                                            </div>
                                        @endforeach
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 column">
                        <div class="apply-job-for-checker">
                            @if (Auth::guard('user')->check())
                                @if ($checkJobTrue == 1)
                                    <a class="apply-thisjob" href="#" style="background: #8b91dd; color: #fff"><i
                                            class="la la-paper-plane"></i>Đã ứng tuyển</a>
                                @else
                                    <a class="apply-thisjob" href="#" data-toggle="modal"
                                        data-target="#exampleModal"><i class="la la-paper-plane"></i>Nộp đơn</a>
                                @endif
                                <div class="apply-alternative btn-like" style="cursor: pointer">
                                    <span><i class="fa fa-heart icon-save-cv"
                                            id="{{ $job->id . ',' . $checklove }}"></i>Lưu</span>
                                @else
                                    <a class="apply-thisjob" href="#"><i class="la la-paper-plane"></i>Nộp đơn</a>
                            @endif
                        </div>
                        <div class="job-overview">
                            <h3>Tổng quan về công việc</h3>
                            <ul>
                                <li><i class="la la-money"></i>
                                    <h3>Mức lương đề xuất</h3><span>{{ $job->getWage->name }}</span>
                                </li>
                                <li><i class="la la-mars-double"></i>
                                    <h3>Giới tính</h3>
                                    @if ($job->sex == 0)
                                        <span>Tất cả</span>
                                    @else
                                        <span>{{ $job->sex }}</span>
                                    @endif
                                </li>
                                <li><i class="la la-puzzle-piece"></i>
                                    <h3>Hình thức làm việc</h3><span>{{ $job->getwk_form->name }}</span>
                                </li>
                                <li><i class="la la-shield"></i>
                                    <h3>Kinh nghiệm</h3><span>{{ $job->getExperience->name }}</span>
                                </li>
                                <li><i class="la la-line-chart "></i>
                                    <h3>Trình độ học vẫn</h3><span>{{ $job->getLevel->name }}</span>
                                </li>
                                <li><i class="la la-calendar-o"></i>
                                    <h3>Hạn nộp hồ sơ</h3><span>{{ $job->end_job_time }}</span>
                                </li>
                            </ul>
                        </div><!-- Job Overview -->
                        <div class="job-location">
                            <h3>Nơi làm việc</h3>
                            <div class="job-lctn-map">
                                <iframe
                                    src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d926917.0482572999!2d-104.57738594649922!3d40.26036964524562!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x54eab584e432360b%3A0x1c3bb99243deb742!2sUnited+States!5e0!3m2!1sen!2s!4v1513784737244"></iframe>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </section>
    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ứng tuyền {{ $job->title }}</h5>
                </div>
                <div class="modal-body">
                    <up-cv
                        :data="{{ json_encode([
                            'cv' => $cv,
                            'urlStore' => route('client.upcv'),
                            'jobId' => $job->id,
                        ]) }}">
                    </up-cv>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/search.blade.php
@extends('layouts.index')
@section('home')
    <form-search-home
        :data="{{ json_encode([
            'lever' => $lever,
            'experience' => $experience,
            'wage' => $wage,
            'skill' => $skill,
            'timework' => $timework,
            'profession' => $profession,
            'majors' => $majors,
            'location' => $location,
            'workingform' => $workingform,
            'request' => $request,
            'job' => $job,
        ]) }}">
    </form-search-home>
@endsection