routes/web.php
<?php

use App\Http\Controllers\Client\CompanyController;
use App\Http\Controllers\Client\EmployerController;
use App\Http\Controllers\Client\MajorsController;
use App\Http\Controllers\Employer\HomeController;
use App\Http\Controllers\Employer\NewEmployerController;
use App\Http\Controllers\Employer\PackageController;
use App\Http\Controllers\Employer\PaymentForEmployerController;
use App\Http\Controllers\Employer\PaymentHistoryController;
use App\Http\Controllers\Employer\ProfileCompanyController;
use App\Http\Controllers\Employer\ProfileEmployerController;
use App\Http\Controllers\Employer\SearchCvController;
use App\Http\Controllers\FagsController;
use App\Http\Controllers\HomeController as ControllersHomeController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\Seeker\ManageController;
use App\Http\Controllers\Seeker\ProfileController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// login
Route::resource('/login', LoginController::class);
Route::prefix('login')->name('login.')->group(function () {
    Route::post('/dang-ky', [LoginController::class, 'register'])->name('register');
    Route::post('/dang-nhap', [LoginController::class, 'store'])->name('store');
});
// home
Route::get('/', [ControllersHomeController::class, 'index'])->name('home');

// xác thực tài khoản
Route::get('xac-thuc-tai-khoan', [LoginController::class, 'activeUser'])->name('activeUser');
//register employer

Route::get('nha-tuyen-dung/dang-ky', [EmployerController::class, 'index'])->name('register');
Route::post('nha-tuyen-dung/dang-ky', [EmployerController::class, 'store'])->name('register.store');

//
Route::prefix('viec-lam')->name('client.')->group(function () {
    Route::get('/{slug}.{id}', [ControllersHomeController::class, 'detail'])->name('detail');
    Route::post('/up-cv', [ControllersHomeController::class, 'upCv'])->name('upcv');
    // love cv
    Route::get('/favourite-love/{id}', [ControllersHomeController::class, 'getDatalove']); // api
    Route::post('/favourite/{id}', [ControllersHomeController::class, 'userFavouriteId']); // api\

    // nganh nghe
    Route::resource('nganh-nghe', MajorsController::class);
});

// client company
Route::prefix('cong-ty')->name('company.')->group(function () {
    Route::get('/{id}', [CompanyController::class, 'detail'])->name('detail');
    Route::get('/', [CompanyController::class, 'index'])->name('index');
});


// faqs
Route::resource('faqs', FagsController::class);

// search job
Route::get('/search', [ControllersHomeController::class, 'search'])->name('home.search');

Route::middleware('checkLogin')->group(function () {
    // client user
    Route::prefix('users')->name('users.')->group(function () {

        Route::prefix('profile')->name('profile.')->group(function () {
            Route::get('/{slug}', [ProfileController::class, 'index'])->name('index');
            Route::post('/update-image-user', [ProfileController::class, 'changeImage'])->name('changeImage');
            Route::post('/on-status-profile', [ProfileController::class, 'onStatus'])->name('onStatus');
            Route::post('/off-status-profile', [ProfileController::class, 'offStatus'])->name('offStatus');
        });
        Route::resource('file', ManageController::class);
        Route::prefix('file')->name('file.')->group(function () {
            Route::get('destroy/{id}', [ManageController::class, 'destroy'])->name('destroy');
            Route::get('/cv/create-cv', [ManageController::class, 'createCv'])->name('createCv');
            Route::post('/cv/create-cv', [ManageController::class, 'createFormCv'])->name('createFormCv');
        });
        Route::get('apply', [ManageController::class, 'apply'])->name('apply');
        Route::get('love', [ManageController::class, 'love'])->name('love');
        Route::prefix('love')->group(function () {
            Route::delete('delete-love-cv', [ManageController::class, 'deleteLoveCv'])->name('deleteLoveCv');
        });
        Route::get('change-password', [ProfileController::class, 'changePassword'])->name('changePassword');
        Route::post('change-password', [ProfileController::class, 'changePasswordSucsses'])->name('changePasswordSucsses');
        // 
        Route::get('get-data-reason/{id}', [ManageController::class, 'getDataReason'])->name('getDataReason');
    });

    // logout
    Route::get('logout', [LoginController::class, 'logout'])->name('logout');

    // ntd 
    Route::middleware('checkEmployer')->group(function () {
        Route::prefix('employers')->name('employer.')->group(function () {
            Route::get('/', [HomeController::class, 'index'])->name('index');
            Route::resource('/new', NewEmployerController::class);
            Route::prefix('/new')->name('new.')->group(function () {
                Route::post('/update/{id}', [NewEmployerController::class, 'update'])->name('update');
                Route::get('/{id}', [NewEmployerController::class, 'destroy'])->name('destroy');
                Route::get('change-status-cv/{id}', [NewEmployerController::class, 'changeStatusCv'])->name('changeStatusCv');
                Route::post('update-reason-cv', [NewEmployerController::class, 'reasonCv'])->name('reasonCv');
                Route::get('get-data-reason/{id}', [NewEmployerController::class, 'getDataReason'])->name('getDataReason');
                Route::get('job/top-new', [NewEmployerController::class, 'topNew'])->name('topNew');
                Route::post('job/top-new', [NewEmployerController::class, 'upTopNew'])->name('upTopNew');
                Route::post('job/delete-top-new/{id}', [NewEmployerController::class, 'deleteTopNew'])->name('deleteTopNew');
                Route::get('cv/get-data-cv-refuse', [NewEmployerController::class, 'refuse'])->name('refuse');
                Route::get('cv/get-data-cv-filter-apply', [NewEmployerController::class, 'filterApply'])->name('filterApply');
                Route::delete('delete/cv/filter-apply/{id}', [NewEmployerController::class, 'deletefilterApply'])->name('deletefilterApply');
            });
            // submitted work
            Route::get('submitted-work', [NewEmployerController::class, 'submittedWork'])->name('submittedWork');
            // 
            Route::resource('/package', PackageController::class);
            Route::resource('/profile', ProfileEmployerController::class);
            Route::resource('/company', ProfileCompanyController::class);
            Route::prefix('/company')->name('company.')->group(function () {
                Route::get('new/business', [ProfileCompanyController::class, 'business'])->name('business');
                Route::post('new/business', [ProfileCompanyController::class, 'ImageAccuracy'])->name('ImageAccuracy');
            });
            Route::prefix('/package')->name('package.')->group(function () {
                Route::post('/payment', [PackageController::class, 'payment'])->name('payment');
                Route::get('package/payment/return', [PackageController::class, 'vnpayReturn'])->name('return');
                Route::get('package/payment/output', [PackageController::class, 'vnpayOutput'])->name('output');
                Route::post('package/payment/update-time/{id}', [PackageController::class, 'updateTimePayment'])->name('updateTimePayment');
                Route::post('package/payment/upgrade-package/{id}', [PackageController::class, 'upgradePackage'])->name('upgradePackage');
            });
            // search cv
            Route::get('search-cv', [SearchCvController::class, 'index'])->name('search.cv');
            Route::get('search-cv/{id}', [SearchCvController::class, 'show'])->name('search.show');
            Route::post('payment-cv', [SearchCvController::class, 'paymentCv'])->name('search.paymentCv');
            Route::post('search-cv/feedback', [SearchCvController::class, 'feedback'])->name('search.feedback');
            Route::get('cv-bought', [SearchCvController::class, 'showCvBought'])->name('cvbought');
            // nap  tiền
            Route::resource('payment-for-emplyer', PaymentForEmployerController::class);
            Route::prefix('/payment-for-emplyer')->name('payment-for-emplyer.')->group(function () {
                Route::get('payment/vnpay-return', [PaymentForEmployerController::class, 'vnpayReturn'])->name('vnpayReturn');
            });
            Route::resource('payment-history', PaymentHistoryController::class);
            // đoi mk
            Route::get('change-password', [HomeController::class, 'changePassword'])->name('changePassword');
            Route::post('change-password', [HomeController::class, 'changePasswordSucsses'])->name('changePasswordSucsses');
        });
    });
});

app/Http/Controllers/Seeker/ManageController.php
<?php

namespace App\Http\Controllers\Seeker;

use App\Http\Controllers\BaseController;
use App\Http\Controllers\Controller;
use App\Models\Favourite;
use App\Models\ProfileUserCv;
use App\Models\Reason;
use App\Models\SaveCv;
use App\Models\UploadCv;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class ManageController extends BaseController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $cv = UploadCv::query()->where('user_id', '=', Auth::guard('user')->user()->id)->get();
        $profileCv = ProfileUserCv::query()->where('user_id', Auth::guard('user')->user()->id)->first();
        return view('seeker.cv.index', [
            'cv' => $cv,
            'profileCv' => $profileCv ?? null,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('seeker.cv.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try {
            $upload = new UploadCv();
            $upload->user_id = Auth::guard('user')->user()->id;
            $upload->title = $request->title;
            if ($request->hasFile('file_cv')) {
                $upload->file_cv = $request->file_cv->storeAs('images/cv', $request->file_cv->hashName());
            }
            $upload->save();
            $this->setFlash(__('Thêm cv mới thành công'));
            return redirect()->route('users.file.index');
        } catch (\Throwable $th) {
            dd($th);
            DB::rollBack();
            $this->setFlash(__('đã có một lỗi không rõ nguyên nhân xảy ra'), 'error');
            return redirect()->back();
        }
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        UploadCv::destroy($id);
        return redirect()->back();
    }
    // công việc đã ứng tuyển
    public function apply()
    {
        $apply = SaveCv::where('save_cv.user_id', Auth::guard('user')->user()->id)
            ->leftjoin('job', 'job.id', '=', 'save_cv.id_job')
            ->join('employer', 'employer.id', '=', 'job.employer_id')
            ->join('company', 'company.id', '=', 'employer.id_company')
            ->Orderby('save_cv.created_at', 'DESC')
            ->select('job.id as id', 'job.slug as slug', 'job.title as title', 'company.id as idCompany', 'company.logo as logo', 'company.name as nameCompany', 'save_cv.created_at as created_at', 'save_cv.status as status', 'save_cv.file_cv as file', 'save_cv.id as id_save_cv')
            ->get();
        return view('seeker.apply.index', [
            'apply' => $apply
        ]);
    }
    // công việc đã yêu thích
    public function love()
    {
        $love = Favourite::query()->where('favourite.user_id', Auth::guard('user')->user()->id)
            ->leftjoin('job', 'job.id', '=', 'favourite.job_id')
            ->leftjoin('wage', 'wage.id', '=', 'job.wage_id')
            ->leftjoin('location', 'location.id', '=', 'job.location_id')
            ->join('employer', 'employer.id', '=', 'job.employer_id')
            ->join('company', 'company.id', '=', 'employer.id_company')
            ->Orderby('favourite.created_at', 'DESC')
            ->select('job.id as id', 'job.slug as slug', 'job.title as title', 'company.id as idCompany', 'company.logo as logo', 'company.name as nameCompany', 'favourite.created_at as created_at', 'wage.name as namewage', 'location.name as nameLocation')
            ->get();
        return view('seeker.love.index', [
            'love' => $love,
        ]);
    }
    public function createCv()
    {
        $skill = ProfileUserCv::query()->where('user_id', Auth::guard('user')->user()->id)->first();
        return view('seeker.cv.createFormCv', [
            'title' => 'Tạo mới CV',
            'user' => ProfileUserCv::query()->where('user_id', Auth::guard('user')->user()->id)->first() ?? null,
            'skill' => $skill ?  $skill->skill : null,
            'project' => $skill ? $skill->project : null,
            'level' => $skill ? $skill->level : null,
            'user_name' => User::query()->find(Auth::guard('user')->user()->id)->name,
            'app' => User::query()->find(Auth::guard('user')->user()->id),
        ]);
        return view('seeker.cv.createFormCv');
    }
    public function deleteLoveCv($id)
    {
    }
    public function createFormCv(Request $request)
    {
        try {
            $user = ProfileUserCv::query()->where('user_id', Auth::guard('user')->user()->id)->first();
            if ($user) {
                $profileUserCv = $user;
            } else {
                $profileUserCv = new ProfileUserCv();
            }
            if ($request->hasFile('images')) {
                $profileUserCv->images = $request->images->storeAs('images/cv', $request->images->hashName());
            }
            // kỹ năng
            $arr_skill = [];
            foreach ($request->nameSkill as $i => $skill) {
                foreach (explode(',', $request->valueSkill) as $key => $value) {
                    if ($i == $key) {
                        $arr_skill[] = [
                            'name' => $skill,
                            'value' => $value
                        ];
                    }
                }
            }
            // dự án
            $array_project = [];
            foreach ($request->nameProject as $i => $project) {
                foreach ($request->deseProject as $key => $value) {
                    if ($i == $key) {
                        $array_project[] = [
                            'name' => $project,
                            'value' => $value
                        ];
                    }
                }
            }
            // học vẫn
            $array_lever = [];
            foreach ($request->timeDucation as $i => $ducation) {
                foreach ($request->nameDucation as $key => $value) {
                    if ($i == $key) {
                        $array_lever[] = [
                            'name' => $ducation,
                            'value' => $value
                        ];
                    }
                }
            }
            $profileUserCv->email = $request->email ?? '';
            $profileUserCv->name = $request->user_name ?? '';
            $profileUserCv->address = $request->address ?? '';
            $profileUserCv->phone = $request->phone ?? '';
            $profileUserCv->skill = $arr_skill ?? '';
            $profileUserCv->about = $request->about ?? '';
            $profileUserCv->level = $array_lever ?? '';
            $profileUserCv->project = $array_project ?? '';
            $profileUserCv->user_id = Auth::guard('user')->user()->id;
            $profileUserCv->status = 0;
            $profileUserCv->link_fb = $request->link_fb ?? '';
            $profileUserCv->majors = $request->majors ?? '';
            $profileUserCv->status_profile = 0;
            $profileUserCv->title =  $request->title ?? '';
            $profileUserCv->link_inta =  $request->link_inta ?? '';
            $profileUserCv->link_sky =  $request->link_sky ?? '';
            $profileUserCv->link_tw =  $request->link_tw ?? '';
            $profileUserCv->save();
            $this->setFlash(__('Cập nhật thành công !'));
            return redirect()->back();
        } catch (\Throwable $th) {
            dd($th->getMessage());
            DB::rollBack();
            $this->setFlash(__('Cập nhật thất bại !'), 'error');
            return redirect()->back();
        }
    }
    public function getDataReason($id)
    {
        $reason = Reason::query()->where('cv_id', $id)->first();
        return [
            'data' => $reason,
            'code' => 200,
        ];
    }
}

resources/views/seeker/changePassword.blade.php
@extends('seeker.layout.index')
@section('main-seeker')
    <div class="container">
        <change-password
            :data="{{ json_encode([
                'urlStore' => route('users.changePasswordSucsses'),
            ]) }}">
        </change-password>
    </div>
@endsection

resources/views/seeker/index.blade.php
@extends('seeker.layout.index')
@section('main-seeker')
    <div class="row">
        <div class="col-lg-8 d-flex align-items-strech">
            <div class="card w-100">
                <div class="card-body">
                    <div class="d-sm-flex d-block align-items-center justify-content-between mb-9">
                        <div class="mb-3 mb-sm-0">
                            <h5 class="card-title fw-semibold">Sales Overview</h5>
                        </div>
                        <div>
                            <select class="form-select">
                                <option value="1">March 2023</option>
                                <option value="2">April 2023</option>
                                <option value="3">May 2023</option>
                                <option value="4">June 2023</option>
                            </select>
                        </div>
                    </div>
                    <div id="chart"></div>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="row">
                <div class="col-lg-12">
                    <!-- Yearly Breakup -->
                    <div class="card overflow-hidden">
                        <div class="card-body p-4">
                            <h5 class="card-title mb-9 fw-semibold">Thông tin cá nhân</h5>
                            <div class="row align-items-center">
                                <div class="row">
                                    <div class="col-md-4" style="text-align: center">
                                        <div class="profile-avatar">
                                            <img src="{{ asset(Auth::guard('user')->user()->images) }}" alt=""
                                                style=" border-radius: 50%;
                                                height: 83px;
                                                max-width: 150px;
                                                width: 83px;">
                                        </div>
                                        <div class="text-center">
                                            <input type="file" name="avatar" style="display: none;" id="img-avatar">
                                            <a href="javascript:void(0)"
                                                style="font-size: 11px; padding: 3px 5px;margin: 6px 0px; color: #777; font-style: italic;"
                                                id="btn-upload-avatar" data-bs-toggle="modal"
                                                data-bs-target="#exampleModal">
                                                Cập nhật ảnh
                                            </a>
                                        </div>
                                    </div>
                                    <div class="col-md-8">
                                        <div>Chào bạn trở lại,</div>
                                        <h4 class="profile-fullname"
                                            style="-webkit-line-clamp: 2;
                                        -webkit-box-orient: vertical;
                                        color: #212f3f;
                                        font-size: 20px;
                                        font-weight: 700;
                                        margin-bottom: 10px;
                                        margin-top: 0;
                                        overflow: hidden;
                                        overflow-wrap: break-word;
                                        position: relative;
                                        text-overflow: ellipsis;">
                                            {{ Auth::guard('user')->user()->name }}</h4>
                                        <div class="account-type vip">
                                            <span
                                                style="background-color: gray;    border-radius: 2px;
                                            color: #fff;
                                            display: inline-block;
                                            font-size: 12px;
                                            padding: 3px 7px;">
                                                Tài khoản đã xác thực
                                            </span>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-xs-12 mt-3">
                                    <btn-toggle
                                        :data="{{ json_encode([
                                            'profileCv' => $profileCv,
                                            'experience' => $experience,
                                            'wage' => $wage,
                                            'skill' => $skill,
                                            'majors' => $majors,
                                            'location' => $location,
                                            'jobSeeker' => $jobSeeker,
                                            'skillSeeker' => $skillSeeker,
                                        ]) }}">
                                    </btn-toggle>
                                    <span class="job-waiting-status-text job-off-show ml-2">
                                        <strong class="text-red">Trạng thái tìm việc</strong>
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-12">
                    <!-- Monthly Earnings -->
                    <div class="card">
                        <div class="card-body">
                            <div class="row alig n-items-start">
                                <div class="col-8">
                                    <h5 class="card-title mb-9 fw-semibold">Số lượng nhà tuyển dụng xem hồ sơ </h5>
                                    <h4 class="fw-semibold mb-3">{{ $countEmployerSeeCv }}</h4>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {{-- modal change image user --}}
        <!-- Modal -->
        <change-image
            :data="{{ json_encode([
                'user' => $user,
                'urlChange' => route('users.profile.changeImage'),
            ]) }}"></change-image>
    </div>
    <div class="row">
        <div class="col-lg-4 d-flex align-items-stretch">
            <div class="card w-100">
                <div class="card-body p-4">
                    <div class="mb-4">
                        <h5 class="card-title fw-semibold">Lịch sử tìm kiếm</h5>
                    </div>
                    @if ($keySearch)
                        <ul class="timeline-widget mb-0 position-relative mb-n5">
                            <li class="timeline-item d-flex position-relative overflow-hidden">
                                <div class="timeline-desc fs-3 text-dark mt-n1 p-2">
                                    @foreach ($keySearch as $item)
                                        <a href="{{ route('home.search') }}?key={{ $item->key }}" class="border"
                                            style="margin-left: 10px">{{ $item->key }}({{ $item->count }})</a>
                                    @endforeach

                                </div>
                            </li>
                        </ul>
                    @endif

                </div>
            </div>
        </div>
        <div class="col-lg-8 d-flex align-items-stretch">
            <div class="card w-100">
                <div class="card-body p-4">
                    <h5 class="card-title fw-semibold mb-4">Công việc đã ứng tuyển</h5>
                    <div class="table-responsive">
                        <table class="table text-nowrap mb-0 align-middle">
                            <thead class="text-dark fs-4">
                                <tr>
                                    <th class="border-bottom-0">
                                        <h6 class="fw-semibold mb-0">#</h6>
                                    </th>
                                    <th class="border-bottom-0">
                                        <h6 class="fw-semibold mb-0">Công việc</h6>
                                    </th>
                                    <th class="border-bottom-0">
                                        <h6 class="fw-semibold mb-0">Địa chỉ</h6>
                                    </th>
                                    <th class="border-bottom-0">
                                        <h6 class="fw-semibold mb-0">Trạng thái</h6>
                                    </th>
                                    <th class="border-bottom-0">
                                        <h6 class="fw-semibold mb-0"></h6>
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($apply as $key => $item)
                                    <tr>
                                        <td class="border-bottom-0">
                                            <h6 class="fw-semibold mb-0">{{ $key + 1 }}</h6>
                                        </td>
                                        <td class="border-bottom-0">
                                            <h6 class="fw-semibold mb-1">{{ $item->title }}</h6>
                                            <span class="fw-normal">{{ $item->majors }}</span>
                                        </td>
                                        <td class="border-bottom-0">
                                            <p class="mb-0 fw-normal">{{ $item->location }}</p>
                                        </td>
                                        <td class="border-bottom-0">
                                            <div class="d-flex align-items-center gap-2">
                                                @if ($item->status == 0)
                                                    <span class="badge bg-danger rounded-3 fw-semibold"
                                                        style="font-size: 12px">chưa xem</span>
                                                @endif
                                                @if ($item->status == 1)
                                                    <span class="badge bg-primary rounded-3 fw-semibold"
                                                        style="font-size: 12px">đã xem</span>
                                                @endif
                                                @if ($item->status == 2)
                                                    <span class="badge bg-dark rounded-3 fw-semibold mb-2"
                                                        style="font-size: 12px;">bị hủy</span>
                                                    <br>
                                                    <a href="#"
                                                        onclick="Reason(JSON.parse('{{ $item }}'))">Lý
                                                        do từ chối</a>
                                                @endif
                                            </div>
                                        </td>
                                        <td class="border-bottom-0">
                                            <a href="{{ route('client.detail', [$item->slug, $item->id]) }}"
                                                class="fw-semibold mb-0"><i class="fas fa-eye"></i></a>
                                        </td>
                                    </tr>
                                @endforeach

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="modalReasonCv" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Lý do
                    </h5>
                </div>
                <div class="modal-body">
                    <div class="title">
                        <span id="dataReasonCv"></span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        async function Reason(id) {
            console.log(id);
            const url = '/users/get-data-reason/' + id.id_save_cv;
            await axios.get(url).then(function(res) {
                $('#dataReasonCv').text(res.data.data.content);
            })
            $('#modalReasonCv').modal('show');
        }
    </script>
@endsection