routes/web.php
<?php

use App\Http\Controllers\Client\CompanyController;
use App\Http\Controllers\Client\EmployerController;
use App\Http\Controllers\Client\MajorsController;
use App\Http\Controllers\Employer\HomeController;
use App\Http\Controllers\Employer\NewEmployerController;
use App\Http\Controllers\Employer\PackageController;
use App\Http\Controllers\Employer\PaymentForEmployerController;
use App\Http\Controllers\Employer\PaymentHistoryController;
use App\Http\Controllers\Employer\ProfileCompanyController;
use App\Http\Controllers\Employer\ProfileEmployerController;
use App\Http\Controllers\Employer\SearchCvController;
use App\Http\Controllers\FagsController;
use App\Http\Controllers\HomeController as ControllersHomeController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\Seeker\ManageController;
use App\Http\Controllers\Seeker\ProfileController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// login
Route::resource('/login', LoginController::class);
Route::prefix('login')->name('login.')->group(function () {
    Route::post('/dang-ky', [LoginController::class, 'register'])->name('register');
    Route::post('/dang-nhap', [LoginController::class, 'store'])->name('store');
});
// home
Route::get('/', [ControllersHomeController::class, 'index'])->name('home');

// xác thực tài khoản
Route::get('xac-thuc-tai-khoan', [LoginController::class, 'activeUser'])->name('activeUser');
//register employer

Route::get('nha-tuyen-dung/dang-ky', [EmployerController::class, 'index'])->name('register');
Route::post('nha-tuyen-dung/dang-ky', [EmployerController::class, 'store'])->name('register.store');

//
Route::prefix('viec-lam')->name('client.')->group(function () {
    Route::get('/{slug}.{id}', [ControllersHomeController::class, 'detail'])->name('detail');
    Route::post('/up-cv', [ControllersHomeController::class, 'upCv'])->name('upcv');
    // love cv
    Route::get('/favourite-love/{id}', [ControllersHomeController::class, 'getDatalove']); // api
    Route::post('/favourite/{id}', [ControllersHomeController::class, 'userFavouriteId']); // api\

    // nganh nghe
    Route::resource('nganh-nghe', MajorsController::class);
});

// client company
Route::prefix('cong-ty')->name('company.')->group(function () {
    Route::get('/{id}', [CompanyController::class, 'detail'])->name('detail');
    Route::get('/', [CompanyController::class, 'index'])->name('index');
});


// faqs
Route::resource('faqs', FagsController::class);

// search job
Route::get('/search', [ControllersHomeController::class, 'search'])->name('home.search');

Route::middleware('checkLogin')->group(function () {
    // client user
    Route::prefix('users')->name('users.')->group(function () {

        Route::prefix('profile')->name('profile.')->group(function () {
            Route::get('/{slug}', [ProfileController::class, 'index'])->name('index');
            Route::post('/update-image-user', [ProfileController::class, 'changeImage'])->name('changeImage');
            Route::post('/on-status-profile', [ProfileController::class, 'onStatus'])->name('onStatus');
            Route::post('/off-status-profile', [ProfileController::class, 'offStatus'])->name('offStatus');
        });
        Route::resource('file', ManageController::class);
        Route::prefix('file')->name('file.')->group(function () {
            Route::get('destroy/{id}', [ManageController::class, 'destroy'])->name('destroy');
            Route::get('/cv/create-cv', [ManageController::class, 'createCv'])->name('createCv');
            Route::post('/cv/create-cv', [ManageController::class, 'createFormCv'])->name('createFormCv');
        });
        Route::get('apply', [ManageController::class, 'apply'])->name('apply');
        Route::get('love', [ManageController::class, 'love'])->name('love');
        Route::prefix('love')->group(function () {
            Route::delete('delete-love-cv', [ManageController::class, 'deleteLoveCv'])->name('deleteLoveCv');
        });
        Route::get('change-password', [ProfileController::class, 'changePassword'])->name('changePassword');
        Route::post('change-password', [ProfileController::class, 'changePasswordSucsses'])->name('changePasswordSucsses');
        // 
        Route::get('get-data-reason/{id}', [ManageController::class, 'getDataReason'])->name('getDataReason');
    });

    // logout
    Route::get('logout', [LoginController::class, 'logout'])->name('logout');

    // ntd 
    Route::middleware('checkEmployer')->group(function () {
        Route::prefix('employers')->name('employer.')->group(function () {
            Route::get('/', [HomeController::class, 'index'])->name('index');
            Route::resource('/new', NewEmployerController::class);
            Route::prefix('/new')->name('new.')->group(function () {
                Route::post('/update/{id}', [NewEmployerController::class, 'update'])->name('update');
                Route::get('/{id}', [NewEmployerController::class, 'destroy'])->name('destroy');
                Route::get('change-status-cv/{id}', [NewEmployerController::class, 'changeStatusCv'])->name('changeStatusCv');
                Route::post('update-reason-cv', [NewEmployerController::class, 'reasonCv'])->name('reasonCv');
                Route::get('get-data-reason/{id}', [NewEmployerController::class, 'getDataReason'])->name('getDataReason');
                Route::get('job/top-new', [NewEmployerController::class, 'topNew'])->name('topNew');
                Route::post('job/top-new', [NewEmployerController::class, 'upTopNew'])->name('upTopNew');
                Route::post('job/delete-top-new/{id}', [NewEmployerController::class, 'deleteTopNew'])->name('deleteTopNew');
                Route::get('cv/get-data-cv-refuse', [NewEmployerController::class, 'refuse'])->name('refuse');
                Route::get('cv/get-data-cv-filter-apply', [NewEmployerController::class, 'filterApply'])->name('filterApply');
                Route::delete('delete/cv/filter-apply/{id}', [NewEmployerController::class, 'deletefilterApply'])->name('deletefilterApply');
            });
            // submitted work
            Route::get('submitted-work', [NewEmployerController::class, 'submittedWork'])->name('submittedWork');
            // 
            Route::resource('/package', PackageController::class);
            Route::resource('/profile', ProfileEmployerController::class);
            Route::resource('/company', ProfileCompanyController::class);
            Route::prefix('/company')->name('company.')->group(function () {
                Route::get('new/business', [ProfileCompanyController::class, 'business'])->name('business');
                Route::post('new/business', [ProfileCompanyController::class, 'ImageAccuracy'])->name('ImageAccuracy');
            });
            Route::prefix('/package')->name('package.')->group(function () {
                Route::post('/payment', [PackageController::class, 'payment'])->name('payment');
                Route::get('package/payment/return', [PackageController::class, 'vnpayReturn'])->name('return');
                Route::get('package/payment/output', [PackageController::class, 'vnpayOutput'])->name('output');
                Route::post('package/payment/update-time/{id}', [PackageController::class, 'updateTimePayment'])->name('updateTimePayment');
                Route::post('package/payment/upgrade-package/{id}', [PackageController::class, 'upgradePackage'])->name('upgradePackage');
            });
            // search cv
            Route::get('search-cv', [SearchCvController::class, 'index'])->name('search.cv');
            Route::get('search-cv/{id}', [SearchCvController::class, 'show'])->name('search.show');
            Route::post('payment-cv', [SearchCvController::class, 'paymentCv'])->name('search.paymentCv');
            Route::post('search-cv/feedback', [SearchCvController::class, 'feedback'])->name('search.feedback');
            Route::get('cv-bought', [SearchCvController::class, 'showCvBought'])->name('cvbought');
            // nap  tiền
            Route::resource('payment-for-emplyer', PaymentForEmployerController::class);
            Route::prefix('/payment-for-emplyer')->name('payment-for-emplyer.')->group(function () {
                Route::get('payment/vnpay-return', [PaymentForEmployerController::class, 'vnpayReturn'])->name('vnpayReturn');
            });
            Route::resource('payment-history', PaymentHistoryController::class);
            // đoi mk
            Route::get('change-password', [HomeController::class, 'changePassword'])->name('changePassword');
            Route::post('change-password', [HomeController::class, 'changePasswordSucsses'])->name('changePasswordSucsses');
        });
    });
});

app/Models/News.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class News extends Model
{
    use HasFactory;
    protected $table = 'news';
    protected $fillable = [
        'id',
        'title',
        'majors_id',
        'new_image',
        'describe',
        'status',
    ];
    public function majors()
    {
        return $this->hasOne(Majors::class, 'id', 'majors_id');
    }
}

app/Http/Controllers/Client/EmployerController.php
<?php

namespace App\Http\Controllers\Client;

use App\Http\Controllers\BaseController;
use App\Models\Employer;
use App\Models\location;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class EmployerController extends BaseController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        return view('client.employer.register', [
            'location' => $this->getlocation()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $name = $this->convertName($request->name);
        if (!$this->checkMailUser($request)) {
            $this->setFlash(__('Email này đã được đăng ký trước đây'), 'error');
            return view('client.employer.register', [
                'location' => $this->getlocation(),
                'request' => $request->all(),
            ]);
        }
        try {
            $user =  User::query()->create([
                'name' => $request->name,
                'email' => $request->email,
                'password' => Hash::make($request->password),
                'role_id' => 2,
                'status' => 2,
                'slug' => $name
            ]);
            $user->save();
            $employer = new Employer();
            $employer->name = $request->name;
            $employer->phone = $request->sdt;
            $employer->sex = $request->sex;
            $employer->namecompany = $request->company;
            $employer->workplace = $request->workplace;
            $employer->address = $request->address;
            $employer->user_id = $user->id;
            $employer->save();
            $this->setFlash(__('đăng ký tài khoản nhà tuyển dụng thành công'));
            return redirect(route('home'));
        } catch (\Throwable $th) {
            DB::rollBack();
            $this->setFlash(__('đã có một lỗi không xác định đã xảy ra, kiểm tra lại thông tin của bạn'), 'error');
            return view('client.employer.register', [
                'location' => $this->getlocation(),
                'request' => $request->all(),
            ]);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Employer/HomeController.php
<?php

namespace App\Http\Controllers\Employer;

use App\Http\Controllers\BaseController;
use App\Http\Controllers\Controller;
use App\Models\AccountPayment;
use App\Models\Employer;
use App\Models\Job;
use App\Models\PaymentHistoryEmployer;
use App\Models\ProfileUserCv;
use App\Models\SaveCv;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;




class HomeController extends BaseController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $checkCompany = Employer::query()->where('user_id', Auth::guard('user')->user()->id)->first();
        // số  lượng bài viết đã đăng
        $job = Job::query()->where('employer_id', $checkCompany->id)->count();
        // số lương hồ sơ đã nhận
        $cv = SaveCv::query()
            ->join('job', 'job.id', '=', 'save_cv.id_job')
            ->join('employer', 'employer.id', '=', 'job.employer_id')
            ->where('job.employer_id', $checkCompany->id)
            ->count();
        // số lượng cv đã  mua
        $tatalecv = ProfileUserCv::query()->where('status', Auth::guard('user')->user()->id)->count();
        // tổng số tiền
        $totalPayment = AccountPayment::where('user_id', Auth::guard('user')->user()->id)->first();
        if ($totalPayment) {
            $totalPayment = $totalPayment->surplus;
        } else {
            $totalPayment = 0;
        }
        // lịch sử giao dịch
        $paymentHistory = PaymentHistoryEmployer::query()->where('user_id', $checkCompany->id)->limit(2)->orderBy('created_at', 'desc')->get();
        // Hồ sơ mới nhận gần đây
        $cvApplyNew = SaveCv::query()
            ->join('job', 'job.id', '=', 'save_cv.id_job')
            ->leftjoin('users', 'users.id', '=', 'save_cv.user_id')
            ->join('employer', 'employer.id', '=', 'job.employer_id')
            ->leftjoin('majors', 'majors.id', '=', 'job.majors_id')
            ->leftjoin('time_work', 'time_work.id', '=', 'job.time_work_id')
            ->where([
                ['employer.user_id', Auth::guard('user')->user()->id],
                // ['save_cv.status', 0],
            ])
            ->orderBy('save_cv.created_at', 'desc')
            ->select('job.id as job_id', 'users.name as user_name', 'users.images as images', 'save_cv.status as status', 'save_cv.id as cv_id', 'save_cv.file_cv as file_cv', 'save_cv.user_id as user_id', 'majors.name as majors_name', 'save_cv.created_at as create_at_sv',  'time_work.name  as time_work_name')
            ->get();
        return view('employer.home', [
            'request' => $request->all(),
            'cv' => $cv ?? 0,
            'totalPayment' => $totalPayment,
            'tatalecv' => $tatalecv ?? 0,
            'job' => $job ?? 0,
            'paymentHistory' => $paymentHistory ?? 0,
            'cvApplyNew' => $cvApplyNew ?? 0,
            'countCvMoth1' => $this->getDataMouth(1, $checkCompany->id, $request->all()),
            'countCvMoth2' => $this->getDataMouth(2, $checkCompany->id, $request->all()),
            'countCvMoth3' => $this->getDataMouth(3, $checkCompany->id, $request->all()),
            'countCvMoth4' => $this->getDataMouth(4, $checkCompany->id, $request->all()),
            'countCvMoth5' => $this->getDataMouth(5, $checkCompany->id, $request->all()),
            'countCvMoth6' =>  $this->getDataMouth(6, $checkCompany->id, $request->all()),
            'countCvMoth7' => $this->getDataMouth(7, $checkCompany->id, $request->all()),
            'countCvMoth8' => $this->getDataMouth(8, $checkCompany->id, $request->all()),
            'countCvMoth9' => $this->getDataMouth(9, $checkCompany->id, $request->all()),
            'countCvMoth10' => $this->getDataMouth(10, $checkCompany->id, $request->all()),
            'countCvMoth11' => $this->getDataMouth(11, $checkCompany->id, $request->all()),
            'countCvMoth12' => $this->getDataMouth(12, $checkCompany->id, $request->all()),
        ]);
    }
    public  function changePassword()
    {
        return  view('employer.changePassword');
    }
    public  function changePasswordSucsses(Request  $request)
    {
        try {
            $user = User::query()->find(Auth::guard('user')->user()->id);
            $user->password = Hash::make($request->password);
            $user->save();
            $this->setFlash(_('Đổi mật khẩu thành công'));
            return redirect()->back();
        } catch (\Throwable $th) {
            DB::rollBack();
            $this->setFlash(_('Đã có một lỗi xảy ra'));
            return redirect()->back();
        }
    }
}

resources/views/employer/new/filter.blade.php
@extends('employer.layout.index')
@section('main-employer')
    <div class="card">
        <div class="card-body">
            <h5 class="card-title fw-semibold mb-4">Danh sách ứng viên bị từ chối</h5>
            <a href="{{ route('employer.submittedWork') }}" class="btn btn-primary">Hồ sơ chưa xem</a>
            <a href="{{ route('employer.new.refuse') }}" style="margin-left: 10px" class="btn btn-primary">Hồ sơ đã bị từ
                tối</a>
            <div class="table-responsive mt-4">
                <table class="table" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th><input type="checkbox" class="js-check-all"></th>
                            <th>Tên ứng viên</th>
                            <th>lý đo</th>
                            <th class="text-center">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($filter as $item)
                            <tr>
                                <td><input type="checkbox" value="{{ $item->id }}" name="id[]" class="js-check-one">
                                <td>{{ $item->user->name }}</td>
                                <td>{{ $item->content }}</td>
                                <td>
                                    <btn-delete :message-confirm="{{ json_encode('Bạn có chắc muốn xóa bài viết?') }}"
                                        :delete-action="{{ json_encode(route('employer.new.deletefilterApply', $item->id)) }}">
                                    </btn-delete>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

resources/views/employer/new/index.blade.php
@extends('employer.layout.index')
@section('main-employer')
    <style>
        .icon-check-very {
            color: rgb(20, 148, 252)
        }
    </style>
    <div class="card">
        <div class="card-body">
            <h5 class="card-title fw-semibold mb-4">Danh sách tin tuyển dụng</h5>
            <a href="{{ route('employer.new.create') }}" class="btn btn-primary">Thêm mới</a>
            <a href="{{ route('employer.new.topNew') }}" class="btn btn-primary" style="margin-left: 10px">Đẩy tim lên Top hiển
                thị</a>
            <div class="table-responsive mt-4">
                <table class="table" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th><input type="checkbox" class="js-check-all"></th>
                            <th>Tiêu đề</th>
                            <th>Ứng tuyển</th>
                            <th>Ngày đăng</th>
                            <th>Ngày hết hạn</th>
                            <th>Trạng thái</th>
                            <th class="text-center">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($job as $item)
                            <tr>
                                <td><input type="checkbox" value="{{ $item->id }}" name="id[]" class="js-check-one">
                                </td>
                                <td>{{ $item->title }}</td>
                                <td><a href="{{ route('employer.new.show', $item->id) }}">{{ count($item->AllCv) }}</a></td>
                                <td>{{ $item->job_time }}</td>
                                <td>{{ $item->end_job_time }}</td>
                                <td><span
                                        class="badge p-1 {{ $item->expired == 0 ? 'bg-success text-white' : 'bg-dark text-white' }}">{{ $item->expired == 1 ? 'Hết hạn' : 'Đang hoạt động' }}</span>
                                </td>
                                <td>
                                    <a href="{{ route('employer.new.edit', $item->id) }}"><i class="fas fa-edit"></i></a>
                                    |
                                    <btn-delete :message-confirm="{{ json_encode('Bạn có chắc muốn xóa bài viết?') }}"
                                        :delete-action="{{ json_encode(route('employer.new.destroy', $item->id)) }}">
                                    </btn-delete>
                                </td>
                            </tr>
                        @endforeach

                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Xác thực tài khoản doanh nghiệp</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body d-flex">
                    <span class="fs-5">
                        - Để sử dụng dịch vụ của chúng tôi, bạn và doanh nghiệp cần xác thực doanh nghiệp bằng 2 bước sau
                        đây: <br>
                        Bước 1: Thêm thông tin công ty <a href="{{ route('employer.company.index') }}">tại đây</a>
                        @if ($company)
                            <span
                                style="margin-right: 410px;
                                margin-top: 3px;
                                float: right;
                                display: flex;
                                justify-content: space-evenly;
                                align-items: center;
                                border: 1px solid rgb(20, 148, 252);
                                border-radius: 50%;
                                width: 20px;
                                height: 20px;">
                                <i class="fas fa-check" style="color: rgb(20, 148, 252); font-size: 10px"></i>
                            </span>
                        @endif

                        <br>
                        Bước 2: Xác thực giấy phép kinh doanh <a href="{{ route('employer.company.business') }}">tại
                            đây</a>
                        @if ($acctiveAccuracy)
                            <span
                                style="margin-right: 350px;
                                margin-top: 5px;
                                float: right;
                                display: flex;
                                justify-content: space-evenly;
                                align-items: center;
                                border: 1px solid rgb(20, 148, 252);
                                border-radius: 50%;
                                width: 20px;
                                height: 20px;">
                                <i class="fas fa-check" style="color: rgb(20, 148, 252); font-size: 10px"></i>
                            </span>
                        @else
                            <span
                                style="margin-right: 225px;
                                margin-top: -1px;
                                float: right;
                                display: flex;
                                justify-content: space-evenly;
                                align-items: center;
                                border-radius: 10px;
                                border: 1px solid rgb(217, 11, 11);
                                width: 143px;
                                height: 28px;
                                color: rgb(217, 11, 11);">
                                Chờ xác thực
                            </span>
                        @endif
                    </span>
                </div>
            </div>
        </div>
    </div>
    <script>
        $(document).ready(function() {
            $('.js-check-all').click(function(e) {
                $('input:checkbox').prop('checked', this.checked);
            });
            if ({!! json_encode($company) !!} && {!! json_encode($acctiveAccuracy) !!}) {
                $('#exampleModal').modal('hidden');
            } else {
                $('#exampleModal').modal('show');
            }

        })
    </script>
@endsection

resources/views/employer/new/topNew.blade.php
@extends('employer.layout.index')
@section('main-employer')
    <div class="card">
        <div class="card-body">
            <h5 class="card-title fw-semibold mb-4">Danh sách tin tuyển dụng trên top</h5>
            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">Thêm
                mới</button>
            <div class="table-responsive mt-4">
                <table class="table" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th><input type="checkbox" class="js-check-all"></th>
                            <th>Tiêu đề</th>
                            <th>Ứng tuyển</th>
                            <th>Ngày đăng</th>
                            <th>Ngày hết hạn</th>
                            <th>Trạng thái</th>
                            <th class="text-center">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($job as $item)
                            <tr>
                                <td><input type="checkbox" value="{{ $item->id }}" name="id[]" class="js-check-one">
                                </td>
                                <td>{{ $item->title }}</td>
                                <td><a href="{{ route('employer.new.show', $item->id) }}">{{ count($item->AllCv) }}</a></td>
                                <td>{{ $item->job_time }}</td>
                                <td>{{ $item->end_job_time }}</td>
                                <td><span
                                        class="badge p-1 {{ $item->status == 1 ? 'bg-success text-white' : 'bg-secondary text-white' }}">{{ $item->status == 0 ? 'Bản nháp' : 'Đang hoạt động' }}</span>
                                </td>
                                <td class="d-flex text-center">
                                    <a href="{{ route('employer.new.edit', $item->id) }}">
                                        <i class="fas fa-edit"></i></a>
                                    <btn-delete-job-top
                                        :message-confirm="{{ json_encode('Bạn có chắc muốn xóa bài viết ra khỏi Top?') }}"
                                        :delete-action="{{ json_encode(route('employer.new.deleteTopNew', $item->id)) }}">
                                    </btn-delete-job-top>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Thêm tin lên Top tuyển dụng</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form action="{{ route('employer.new.upTopNew') }}" method="post"
                        class="user-chosen-select-container">
                        @csrf
                        <p style="text-align: center ">Số lượng bài bài viết được tải lên top của bạn phụ thuộc vào gói
                            cước mà bạn đã mua <a href="">Xem chi tiết ở đây</a>
                        </p>
                        <select name="job[]" class="form-control">
                            @foreach ($allJob as $item)
                                <option value="{{ $item->id }}">{{ $item->title }}</option>
                            @endforeach
                        </select>
                        <button class="btn btn-info font-weight-medium color-text-2 mr-1  text-white"
                            style="margin-left: 36%; width: 140px; margin-top: 20px" type="submit">Cập nhật ngay
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script>
        var $j = jQuery.noConflict();
        $j(document).ready(function() {
            $j('.js-check-all').click(function(e) {
                $j('input:checkbox').prop('checked', this.checked);
            });
            $j('#select2').select2();
        })
    </script>
@endsection