routes/web.php
<?php

use App\Http\Controllers\Client\CompanyController;
use App\Http\Controllers\Client\EmployerController;
use App\Http\Controllers\Client\MajorsController;
use App\Http\Controllers\Employer\HomeController;
use App\Http\Controllers\Employer\NewEmployerController;
use App\Http\Controllers\Employer\PackageController;
use App\Http\Controllers\Employer\PaymentForEmployerController;
use App\Http\Controllers\Employer\PaymentHistoryController;
use App\Http\Controllers\Employer\ProfileCompanyController;
use App\Http\Controllers\Employer\ProfileEmployerController;
use App\Http\Controllers\Employer\SearchCvController;
use App\Http\Controllers\FagsController;
use App\Http\Controllers\HomeController as ControllersHomeController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\Seeker\ManageController;
use App\Http\Controllers\Seeker\ProfileController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// login
Route::resource('/login', LoginController::class);
Route::prefix('login')->name('login.')->group(function () {
    Route::post('/dang-ky', [LoginController::class, 'register'])->name('register');
    Route::post('/dang-nhap', [LoginController::class, 'store'])->name('store');
});
// home
Route::get('/', [ControllersHomeController::class, 'index'])->name('home');

// xác thực tài khoản
Route::get('xac-thuc-tai-khoan', [LoginController::class, 'activeUser'])->name('activeUser');
//register employer

Route::get('nha-tuyen-dung/dang-ky', [EmployerController::class, 'index'])->name('register');
Route::post('nha-tuyen-dung/dang-ky', [EmployerController::class, 'store'])->name('register.store');

//
Route::prefix('viec-lam')->name('client.')->group(function () {
    Route::get('/{slug}.{id}', [ControllersHomeController::class, 'detail'])->name('detail');
    Route::post('/up-cv', [ControllersHomeController::class, 'upCv'])->name('upcv');
    // love cv
    Route::get('/favourite-love/{id}', [ControllersHomeController::class, 'getDatalove']); // api
    Route::post('/favourite/{id}', [ControllersHomeController::class, 'userFavouriteId']); // api\

    // nganh nghe
    Route::resource('nganh-nghe', MajorsController::class);
});

// client company
Route::prefix('cong-ty')->name('company.')->group(function () {
    Route::get('/{id}', [CompanyController::class, 'detail'])->name('detail');
    Route::get('/', [CompanyController::class, 'index'])->name('index');
});


// faqs
Route::resource('faqs', FagsController::class);

// search job
Route::get('/search', [ControllersHomeController::class, 'search'])->name('home.search');

Route::middleware('checkLogin')->group(function () {
    // client user
    Route::prefix('users')->name('users.')->group(function () {

        Route::prefix('profile')->name('profile.')->group(function () {
            Route::get('/{slug}', [ProfileController::class, 'index'])->name('index');
            Route::post('/update-image-user', [ProfileController::class, 'changeImage'])->name('changeImage');
            Route::post('/on-status-profile', [ProfileController::class, 'onStatus'])->name('onStatus');
            Route::post('/off-status-profile', [ProfileController::class, 'offStatus'])->name('offStatus');
        });
        Route::resource('file', ManageController::class);
        Route::prefix('file')->name('file.')->group(function () {
            Route::get('destroy/{id}', [ManageController::class, 'destroy'])->name('destroy');
            Route::get('/cv/create-cv', [ManageController::class, 'createCv'])->name('createCv');
            Route::post('/cv/create-cv', [ManageController::class, 'createFormCv'])->name('createFormCv');
        });
        Route::get('apply', [ManageController::class, 'apply'])->name('apply');
        Route::get('love', [ManageController::class, 'love'])->name('love');
        Route::prefix('love')->group(function () {
            Route::delete('delete-love-cv', [ManageController::class, 'deleteLoveCv'])->name('deleteLoveCv');
        });
        Route::get('change-password', [ProfileController::class, 'changePassword'])->name('changePassword');
        Route::post('change-password', [ProfileController::class, 'changePasswordSucsses'])->name('changePasswordSucsses');
        // 
        Route::get('get-data-reason/{id}', [ManageController::class, 'getDataReason'])->name('getDataReason');
    });

    // logout
    Route::get('logout', [LoginController::class, 'logout'])->name('logout');

    // ntd 
    Route::middleware('checkEmployer')->group(function () {
        Route::prefix('employers')->name('employer.')->group(function () {
            Route::get('/', [HomeController::class, 'index'])->name('index');
            Route::resource('/new', NewEmployerController::class);
            Route::prefix('/new')->name('new.')->group(function () {
                Route::post('/update/{id}', [NewEmployerController::class, 'update'])->name('update');
                Route::get('/{id}', [NewEmployerController::class, 'destroy'])->name('destroy');
                Route::get('change-status-cv/{id}', [NewEmployerController::class, 'changeStatusCv'])->name('changeStatusCv');
                Route::post('update-reason-cv', [NewEmployerController::class, 'reasonCv'])->name('reasonCv');
                Route::get('get-data-reason/{id}', [NewEmployerController::class, 'getDataReason'])->name('getDataReason');
                Route::get('job/top-new', [NewEmployerController::class, 'topNew'])->name('topNew');
                Route::post('job/top-new', [NewEmployerController::class, 'upTopNew'])->name('upTopNew');
                Route::post('job/delete-top-new/{id}', [NewEmployerController::class, 'deleteTopNew'])->name('deleteTopNew');
                Route::get('cv/get-data-cv-refuse', [NewEmployerController::class, 'refuse'])->name('refuse');
                Route::get('cv/get-data-cv-filter-apply', [NewEmployerController::class, 'filterApply'])->name('filterApply');
                Route::delete('delete/cv/filter-apply/{id}', [NewEmployerController::class, 'deletefilterApply'])->name('deletefilterApply');
            });
            // submitted work
            Route::get('submitted-work', [NewEmployerController::class, 'submittedWork'])->name('submittedWork');
            // 
            Route::resource('/package', PackageController::class);
            Route::resource('/profile', ProfileEmployerController::class);
            Route::resource('/company', ProfileCompanyController::class);
            Route::prefix('/company')->name('company.')->group(function () {
                Route::get('new/business', [ProfileCompanyController::class, 'business'])->name('business');
                Route::post('new/business', [ProfileCompanyController::class, 'ImageAccuracy'])->name('ImageAccuracy');
            });
            Route::prefix('/package')->name('package.')->group(function () {
                Route::post('/payment', [PackageController::class, 'payment'])->name('payment');
                Route::get('package/payment/return', [PackageController::class, 'vnpayReturn'])->name('return');
                Route::get('package/payment/output', [PackageController::class, 'vnpayOutput'])->name('output');
                Route::post('package/payment/update-time/{id}', [PackageController::class, 'updateTimePayment'])->name('updateTimePayment');
                Route::post('package/payment/upgrade-package/{id}', [PackageController::class, 'upgradePackage'])->name('upgradePackage');
            });
            // search cv
            Route::get('search-cv', [SearchCvController::class, 'index'])->name('search.cv');
            Route::get('search-cv/{id}', [SearchCvController::class, 'show'])->name('search.show');
            Route::post('payment-cv', [SearchCvController::class, 'paymentCv'])->name('search.paymentCv');
            Route::post('search-cv/feedback', [SearchCvController::class, 'feedback'])->name('search.feedback');
            Route::get('cv-bought', [SearchCvController::class, 'showCvBought'])->name('cvbought');
            // nap  tiền
            Route::resource('payment-for-emplyer', PaymentForEmployerController::class);
            Route::prefix('/payment-for-emplyer')->name('payment-for-emplyer.')->group(function () {
                Route::get('payment/vnpay-return', [PaymentForEmployerController::class, 'vnpayReturn'])->name('vnpayReturn');
            });
            Route::resource('payment-history', PaymentHistoryController::class);
            // đoi mk
            Route::get('change-password', [HomeController::class, 'changePassword'])->name('changePassword');
            Route::post('change-password', [HomeController::class, 'changePasswordSucsses'])->name('changePasswordSucsses');
        });
    });
});

app/Http/Controllers/Seeker/ManageController.php
<?php

namespace App\Http\Controllers\Seeker;

use App\Http\Controllers\BaseController;
use App\Http\Controllers\Controller;
use App\Models\Favourite;
use App\Models\ProfileUserCv;
use App\Models\Reason;
use App\Models\SaveCv;
use App\Models\UploadCv;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class ManageController extends BaseController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $cv = UploadCv::query()->where('user_id', '=', Auth::guard('user')->user()->id)->get();
        $profileCv = ProfileUserCv::query()->where('user_id', Auth::guard('user')->user()->id)->first();
        return view('seeker.cv.index', [
            'cv' => $cv,
            'profileCv' => $profileCv ?? null,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('seeker.cv.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try {
            $upload = new UploadCv();
            $upload->user_id = Auth::guard('user')->user()->id;
            $upload->title = $request->title;
            if ($request->hasFile('file_cv')) {
                $upload->file_cv = $request->file_cv->storeAs('images/cv', $request->file_cv->hashName());
            }
            $upload->save();
            $this->setFlash(__('Thêm cv mới thành công'));
            return redirect()->route('users.file.index');
        } catch (\Throwable $th) {
            dd($th);
            DB::rollBack();
            $this->setFlash(__('đã có một lỗi không rõ nguyên nhân xảy ra'), 'error');
            return redirect()->back();
        }
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        UploadCv::destroy($id);
        return redirect()->back();
    }
    // công việc đã ứng tuyển
    public function apply()
    {
        $apply = SaveCv::where('save_cv.user_id', Auth::guard('user')->user()->id)
            ->leftjoin('job', 'job.id', '=', 'save_cv.id_job')
            ->join('employer', 'employer.id', '=', 'job.employer_id')
            ->join('company', 'company.id', '=', 'employer.id_company')
            ->Orderby('save_cv.created_at', 'DESC')
            ->select('job.id as id', 'job.slug as slug', 'job.title as title', 'company.id as idCompany', 'company.logo as logo', 'company.name as nameCompany', 'save_cv.created_at as created_at', 'save_cv.status as status', 'save_cv.file_cv as file', 'save_cv.id as id_save_cv')
            ->get();
        return view('seeker.apply.index', [
            'apply' => $apply
        ]);
    }
    // công việc đã yêu thích
    public function love()
    {
        $love = Favourite::query()->where('favourite.user_id', Auth::guard('user')->user()->id)
            ->leftjoin('job', 'job.id', '=', 'favourite.job_id')
            ->leftjoin('wage', 'wage.id', '=', 'job.wage_id')
            ->leftjoin('location', 'location.id', '=', 'job.location_id')
            ->join('employer', 'employer.id', '=', 'job.employer_id')
            ->join('company', 'company.id', '=', 'employer.id_company')
            ->Orderby('favourite.created_at', 'DESC')
            ->select('job.id as id', 'job.slug as slug', 'job.title as title', 'company.id as idCompany', 'company.logo as logo', 'company.name as nameCompany', 'favourite.created_at as created_at', 'wage.name as namewage', 'location.name as nameLocation')
            ->get();
        return view('seeker.love.index', [
            'love' => $love,
        ]);
    }
    public function createCv()
    {
        $skill = ProfileUserCv::query()->where('user_id', Auth::guard('user')->user()->id)->first();
        return view('seeker.cv.createFormCv', [
            'title' => 'Tạo mới CV',
            'user' => ProfileUserCv::query()->where('user_id', Auth::guard('user')->user()->id)->first() ?? null,
            'skill' => $skill ?  $skill->skill : null,
            'project' => $skill ? $skill->project : null,
            'level' => $skill ? $skill->level : null,
            'user_name' => User::query()->find(Auth::guard('user')->user()->id)->name,
            'app' => User::query()->find(Auth::guard('user')->user()->id),
        ]);
        return view('seeker.cv.createFormCv');
    }
    public function deleteLoveCv($id)
    {
    }
    public function createFormCv(Request $request)
    {
        try {
            $user = ProfileUserCv::query()->where('user_id', Auth::guard('user')->user()->id)->first();
            if ($user) {
                $profileUserCv = $user;
            } else {
                $profileUserCv = new ProfileUserCv();
            }
            if ($request->hasFile('images')) {
                $profileUserCv->images = $request->images->storeAs('images/cv', $request->images->hashName());
            }
            // kỹ năng
            $arr_skill = [];
            foreach ($request->nameSkill as $i => $skill) {
                foreach (explode(',', $request->valueSkill) as $key => $value) {
                    if ($i == $key) {
                        $arr_skill[] = [
                            'name' => $skill,
                            'value' => $value
                        ];
                    }
                }
            }
            // dự án
            $array_project = [];
            foreach ($request->nameProject as $i => $project) {
                foreach ($request->deseProject as $key => $value) {
                    if ($i == $key) {
                        $array_project[] = [
                            'name' => $project,
                            'value' => $value
                        ];
                    }
                }
            }
            // học vẫn
            $array_lever = [];
            foreach ($request->timeDucation as $i => $ducation) {
                foreach ($request->nameDucation as $key => $value) {
                    if ($i == $key) {
                        $array_lever[] = [
                            'name' => $ducation,
                            'value' => $value
                        ];
                    }
                }
            }
            $profileUserCv->email = $request->email ?? '';
            $profileUserCv->name = $request->user_name ?? '';
            $profileUserCv->address = $request->address ?? '';
            $profileUserCv->phone = $request->phone ?? '';
            $profileUserCv->skill = $arr_skill ?? '';
            $profileUserCv->about = $request->about ?? '';
            $profileUserCv->level = $array_lever ?? '';
            $profileUserCv->project = $array_project ?? '';
            $profileUserCv->user_id = Auth::guard('user')->user()->id;
            $profileUserCv->status = 0;
            $profileUserCv->link_fb = $request->link_fb ?? '';
            $profileUserCv->majors = $request->majors ?? '';
            $profileUserCv->status_profile = 0;
            $profileUserCv->title =  $request->title ?? '';
            $profileUserCv->link_inta =  $request->link_inta ?? '';
            $profileUserCv->link_sky =  $request->link_sky ?? '';
            $profileUserCv->link_tw =  $request->link_tw ?? '';
            $profileUserCv->save();
            $this->setFlash(__('Cập nhật thành công !'));
            return redirect()->back();
        } catch (\Throwable $th) {
            dd($th->getMessage());
            DB::rollBack();
            $this->setFlash(__('Cập nhật thất bại !'), 'error');
            return redirect()->back();
        }
    }
    public function getDataReason($id)
    {
        $reason = Reason::query()->where('cv_id', $id)->first();
        return [
            'data' => $reason,
            'code' => 200,
        ];
    }
}

resources/views/seeker/layout/header.blade.php
<header class="app-header">
    <nav class="navbar navbar-expand-lg navbar-light">
        <ul class="navbar-nav">
            <li class="nav-item d-block d-xl-none">
                <a class="nav-link sidebartoggler nav-icon-hover" id="headerCollapse"
                    href="javascript:void(0)">
                    <i class="ti ti-menu-2"></i>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link nav-icon-hover" href="javascript:void(0)">
                    <i class="ti ti-bell-ringing"></i>
                    <div class="notification bg-primary rounded-circle"></div>
                </a>
            </li>
        </ul>
    </nav>
</header>

resources/views/seeker/layout/index.blade.php
<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>user</title>
    <link rel="shortcut icon" type="image/png" href="{{ asset('employer/images/logos/favicon.png') }}" />
    <link rel="stylesheet" href="{{ asset('employer/css/styles.min.css') }}" />
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link href="{{ asset('asset/vendor/datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.js"></script>
    <script src="{{ asset('js/user.js') }}?t={{ time() }}" defer></script>


    <script>
        window.Laravel = {!! json_encode(
            [
                'csrfToken' => csrf_token(),
                'baseUrl' => url('/'),
            ],
            JSON_UNESCAPED_UNICODE,
        ) !!};
    </script>
</head>

<body id="app">
    <!--  Body Wrapper -->
    <div class="page-wrapper" id="main-wrapper" data-layout="vertical" data-navbarbg="skin6" data-sidebartype="full"
        data-sidebar-position="fixed" data-header-position="fixed">
        <!-- Sidebar Start -->
        @include('seeker.layout.sidebar')
        <!--  Sidebar End -->
        <!--  Main wrapper -->
        <div class="body-wrapper">
            <!--  Header Start -->
            @include('seeker.layout.header')
            <!--  Header End -->
            <div class="container-fluid">
                @if (session()->get('Message.flash'))
                    <notyf :data="{{ json_encode(session()->get('Message.flash')[0]) }}"></notyf>
                @endif
                @php
                    session()->forget('Message.flash');
                @endphp
                <!--  Row 1 -->
                @yield('main-seeker')
                <div class="py-6 px-6 text-center">
                    <p class="mb-0 fs-4">Design and Developed by <a href="https://adminmart.com/" target="_blank"
                            class="pe-1 text-primary text-decoration-underline">AdminMart.com</a> Distributed by <a
                            href="https://themewagon.com">ThemeWagon</a>
                    </p>
                </div>
                <div class="loading-div hidden">
                    <div class="loader-img"></div>
                </div>
            </div>
        </div>
    </div>
    <script src="{{ asset('employer/libs/jquery/dist/jquery.min.js') }}"></script>
    <script src="{{ asset('employer/libs/bootstrap/dist/js/bootstrap.bundle.min.js') }}"></script>
    <script src="{{ asset('employer/js/sidebarmenu.js') }}"></script>
    <script src="{{ asset('employer/js/app.min.js') }}"></script>
    <script src="{{ asset('employer/libs/apexcharts/dist/apexcharts.min.js') }}"></script>
    <script src="{{ asset('employer/libs/simplebar/dist/simplebar.js') }}"></script>
    <script src="{{ asset('employer/js/dashboard.js') }}"></script>
    <script src="{{ asset('asset/vendor/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('asset/vendor/datatables/dataTables.bootstrap4.min.js') }}"></script>

    <!-- Page level custom scripts -->
    <script src="{{ asset('asset/js/demo/datatables-demo.js') }}"></script>
</body>

</html>

resources/views/seeker/layout/sidebar.blade.php
<aside class="left-sidebar">
    <!-- Sidebar scroll-->
    <div>
        <div class="brand-logo d-flex align-items-center justify-content-between">
            <a href="{{ route('home') }}" class="text-nowrap logo-img">
                <img src="{{ asset('home/images/resource/logo.png') }}" width="180" alt="" />
            </a>
            <div class="close-btn d-xl-none d-block sidebartoggler cursor-pointer" id="sidebarCollapse">
                <i class="ti ti-x fs-8"></i>
            </div>
        </div>
        <!-- Sidebar navigation-->
        <nav class="sidebar-nav scroll-sidebar" data-simplebar="">
            <ul id="sidebarnav">
                <li class="nav-small-cap">
                    <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
                    <span class="hide-menu">Home</span>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link" href="{{ route('users.profile.index', Auth::guard('user')->user()->slug) }}"
                        aria-expanded="false">
                        <span>
                            <i class="ti ti-layout-dashboard"></i>
                        </span>
                        <span class="hide-menu">Thông Tin cá nhân</span>
                    </a>
                </li>
                <li class="nav-small-cap">
                    <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
                    <span class="hide-menu">Chức năng</span>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link" href="{{ route('users.love') }}" aria-expanded="false">
                        <span>
                            <i class="ti ti-article"></i>
                        </span>
                        <span class="hide-menu">Công việc đã yêu thích</span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link" href="{{ route('users.apply') }}" aria-expanded="false">
                        <span>
                            <i class="ti ti-alert-circle"></i>
                        </span>
                        <span class="hide-menu">công việc đã ứng tuyển</span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link" href="{{ route('users.file.index') }}" aria-expanded="false">
                        <span>
                            <i class="ti ti-cards"></i>
                        </span>
                        <span class="hide-menu">Quản lý CV</span>
                    </a>
                </li>

                </li>
                <li class="nav-small-cap">
                    <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
                    <span class="hide-menu">Của tôi</span>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link" href="{{ route('users.changePassword') }}" aria-expanded="false">
                        <span>
                            <i class="ti ti-login"></i>
                        </span>
                        <span class="hide-menu">Đổi mật khẩu</span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link" href="{{ route('logout') }}" aria-expanded="false">
                        <span>
                            <i class="ti ti-user-plus"></i>
                        </span>
                        <span class="hide-menu">Đăng xuất</span>
                    </a>
                </li>
            </ul>
        </nav>
        <!-- End Sidebar navigation -->
    </div>
    <!-- End Sidebar scroll-->
</aside>